---
title: "Analyzing NYC Restaurant Inspections"
author: Maggie Hsu
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data(rest_inspec)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
#Boxplot comparing restaurant rating distributions by borough
rest_inspec |> #distribution of scores by borough
  filter(is.na(boro)==FALSE, boro != "Missing") |> #Remove NAs and  observations with missing borough values
  mutate(boro = fct_reorder(boro, score)) |> 
    plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
#Compare zip code to scores
rest_inspec |>
  mutate(label = str_c("Score", score)) |> 
  plot_ly(
    x = ~zipcode, y = ~score, type = "scatter", mode = "markers",
    color = ~zipcode, text = ~label, alpha = 0.5) |>
  layout(xaxis = list(tickformat = "digits"))
```

### Chart C

```{r}
#Warning type based on the grade of restaurant the warning was spotted at
rest_inspec |>
mutate(critical_flag = fct_reorder(critical_flag, grade)) |> 
plot_ly(x = ~grade, y = ~critical_flag, type = 'bar', color= ~critical_flag) |>
  layout(yaxis = list(title = "Number of Warnings"), barmode = 'group')
#Warnings from restaurants with unknown grades were omitted by R
```